'use client'

import React, { useState, useRef } from 'react'
import { Zap, Download, FileText, Settings, Eye } from 'lucide-react'
// import { ImageProcessor } from '@/lib/imageProcessor'
// import { LUTGenerator as LUTGen, LUTConfig } from '@/lib/lutGenerator'

interface LutGeneratorProps {
  referenceImage: File | null
  targetColor: string
}

interface LutPreview {
  before: string
  after: string
}

export default function LutGenerator({ referenceImage, targetColor }: LutGeneratorProps) {
  const [isGenerating, setIsGenerating] = useState(false)
  const [lutPreview, setLutPreview] = useState<LutPreview | null>(null)
  const [lutData, setLutData] = useState<{ cube: string; threeDL: string } | null>(null)
  const [lutName, setLutName] = useState('Custom_LUT')
  const [imageAnalysis, setImageAnalysis] = useState<any>(null)
  const canvasRef = useRef<HTMLCanvasElement>(null)

  // const imageProcessor = new ImageProcessor()
  // const lutGenerator = new LUTGen({
  //   size: 32,
  //   name: lutName,
  //   description: 'Generated by LUT Maker AI'
  // })

  const generateLUT = async () => {
    if (!referenceImage) return

    setIsGenerating(true)
    
    try {
      // Simulate LUT generation
      await new Promise(resolve => setTimeout(resolve, 2000))
      
      // Generate simple LUT content
      const cubeContent = generateSimpleCUBELUT()
      const threeDLContent = generateSimple3DLLUT()
      
      setLutData({ cube: cubeContent, threeDL: threeDLContent })
      
      // Generate preview
      const img = await loadImage(referenceImage)
      setLutPreview({ before: img.src, after: img.src })
      
    } catch (error) {
      console.error('Error generating LUT:', error)
    } finally {
      setIsGenerating(false)
    }
  }

  const loadImage = (file: File): Promise<HTMLImageElement> => {
    return new Promise((resolve, reject) => {
      const img = new Image()
      img.onload = () => resolve(img)
      img.onerror = reject
      img.src = URL.createObjectURL(file)
    })
  }

  const generateSimpleCUBELUT = (): string => {
    let content = `TITLE "${lutName}"\n\n`
    content += `LUT_3D_SIZE 32\n\n`
    
    for (let b = 0; b < 32; b++) {
      for (let g = 0; g < 32; g++) {
        for (let r = 0; r < 32; r++) {
          const inputR = r / 31
          const inputG = g / 31
          const inputB = b / 31
          
          // Simple color transformation
          const outputR = Math.min(1, inputR * 1.2)
          const outputG = Math.min(1, inputG * 1.1)
          const outputB = Math.min(1, inputB * 1.3)
          
          content += `${outputR.toFixed(6)} ${outputG.toFixed(6)} ${outputB.toFixed(6)}\n`
        }
      }
    }
    
    return content
  }

  const generateSimple3DLLUT = (): string => {
    let content = `3DMESH\n`
    content += `Mesh 0 32\n`
    
    const meshValues: number[] = []
    for (let i = 0; i < 32; i++) {
      meshValues.push(Math.round((i / 31) * 4095))
    }
    content += meshValues.join(' ') + '\n'
    
    for (let b = 0; b < 32; b++) {
      for (let g = 0; g < 32; g++) {
        for (let r = 0; r < 32; r++) {
          const inputR = r / 31
          const inputG = g / 31
          const inputB = b / 31
          
          const outputR = Math.min(1, inputR * 1.2)
          const outputG = Math.min(1, inputG * 1.1)
          const outputB = Math.min(1, inputB * 1.3)
          
          const r12bit = Math.round(outputR * 4095)
          const g12bit = Math.round(outputG * 4095)
          const b12bit = Math.round(outputB * 4095)
          
          content += `${r12bit} ${g12bit} ${b12bit}\n`
        }
      }
    }
    
    return content
  }

  const downloadLUT = (format: 'cube' | '3dl') => {
    if (!lutData) return

    const content = format === 'cube' ? lutData.cube : lutData.threeDL
    const filename = `${lutName}.${format}`

    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <div className="card max-w-4xl mx-auto">
      <h3 className="text-2xl font-bold mb-6 text-center text-white flex items-center justify-center gap-3">
        <Zap className="w-7 h-7 text-primary-400" />
        Generador de LUT
      </h3>

      <div className="space-y-6">
        {/* LUT Name Input */}
        <div>
          <label className="block text-sm font-medium text-dark-300 mb-2">
            Nombre del LUT
          </label>
          <input
            type="text"
            value={lutName}
            onChange={(e) => setLutName(e.target.value)}
            className="input-field w-full"
            placeholder="Mi_LUT_Personalizado"
          />
        </div>

        {/* Generate Button */}
        <div className="flex justify-center">
          <button
            onClick={generateLUT}
            disabled={!referenceImage || isGenerating}
            className={`btn-primary flex items-center gap-3 px-8 py-4 text-lg ${
              !referenceImage || isGenerating 
                ? 'opacity-50 cursor-not-allowed' 
                : 'hover:shadow-2xl'
            }`}
          >
            {isGenerating ? (
              <>
                <div className="animate-spin w-6 h-6 border-2 border-white border-t-transparent rounded-full"></div>
                <span>Generando LUT...</span>
              </>
            ) : (
              <>
                <Zap className="w-6 h-6" />
                <span>Generar LUT</span>
              </>
            )}
          </button>
        </div>

        {/* LUT Preview */}
        {lutPreview && (
          <div className="grid md:grid-cols-2 gap-6">
            <div className="text-center">
              <h4 className="text-lg font-semibold text-white mb-3">Antes</h4>
              <div className="aspect-video bg-dark-800 rounded-xl overflow-hidden">
                <img
                  src={lutPreview.before}
                  alt="Antes"
                  className="w-full h-full object-cover"
                />
              </div>
            </div>
            <div className="text-center">
              <h4 className="text-lg font-semibold text-white mb-3">Después</h4>
              <div className="aspect-video bg-dark-800 rounded-xl overflow-hidden">
                <img
                  src={lutPreview.after}
                  alt="Después"
                  className="w-full h-full object-cover"
                />
              </div>
            </div>
          </div>
        )}

        {/* Download Options */}
        {lutData && (
          <div className="space-y-4">
            <h4 className="text-lg font-semibold text-white text-center">
              Descargar LUT
            </h4>
            
            <div className="grid md:grid-cols-2 gap-4">
              <button
                onClick={() => downloadLUT('cube')}
                className="btn-secondary flex items-center justify-center gap-3"
              >
                <FileText className="w-5 h-5" />
                <span>Formato .cube</span>
                <span className="text-xs text-dark-400">(DaVinci Resolve)</span>
              </button>
              
              <button
                onClick={() => downloadLUT('3dl')}
                className="btn-secondary flex items-center justify-center gap-3"
              >
                <FileText className="w-5 h-5" />
                <span>Formato .3dl</span>
                <span className="text-xs text-dark-400">(Premiere Pro)</span>
              </button>
            </div>

            {/* LUT Info */}
            {imageAnalysis && (
              <div className="p-4 bg-dark-800/50 rounded-xl">
                <h5 className="font-semibold text-white mb-3">Información del LUT Generado:</h5>
                <div className="grid md:grid-cols-2 gap-4 text-sm">
                  <div>
                    <span className="text-dark-400">Tamaño:</span>
                    <span className="ml-2 text-white">32³ (32,768 puntos)</span>
                  </div>
                  <div>
                    <span className="text-dark-400">Colores analizados:</span>
                    <span className="ml-2 text-white">{imageAnalysis.dominantColors.length}</span>
                  </div>
                  <div>
                    <span className="text-dark-400">Brillo original:</span>
                    <span className="ml-2 text-white">{Math.round(imageAnalysis.brightness)}</span>
                  </div>
                  <div>
                    <span className="text-dark-400">Contraste:</span>
                    <span className="ml-2 text-white">{imageAnalysis.contrast.toFixed(1)}</span>
                  </div>
                </div>
              </div>
            )}

            {/* Usage Instructions */}
            <div className="p-4 bg-dark-800/50 rounded-xl">
              <h5 className="font-semibold text-white mb-2">Instrucciones de Uso:</h5>
              <ul className="text-sm text-dark-300 space-y-1">
                <li>• <strong>DaVinci Resolve:</strong> Ve a Color → LUTs → Importar LUTs</li>
                <li>• <strong>Premiere Pro:</strong> Efectos → Color Correction → Lumetri Color → Creative → Look</li>
                <li>• <strong>After Effects:</strong> Efectos → Color Correction → Lumetri Color</li>
                <li>• <strong>Final Cut Pro:</strong> Inspector → Color → LUT</li>
              </ul>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}